name: iOS
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: xcode-select -p
    - run: pod install
      working-directory: ios
      name: Install pod dependencies

    - name: Build iOS (debug)
      run: "xcodebuild \
        -workspace ios/reactnativetest.xcworkspace \
        -scheme reactnativetest \
        clean archive \
        -sdk iphoneos \
        -configuration Debug \
        -archivePath $PWD/reactnativetest \
        CODE_SIGNING_ALLOWED=NO"

    - name: Compress .xcarchive
      run: zip -r -9 reactnativetest.xcarchive.zip $PWD/reactnativetest.xcarchive/

    - uses: actions/upload-artifact@v2
      with:
        name: ios-xarchive
        path: reactnativetest.xcarchive.zip