name: iOS
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: sudo xcode-select -s /Applications/Xcode_12.app
    - run: pod install
      working-directory: ios
      name: Install pod dependencies

    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}

    - name: Build iOS (debug)
      run: "xcodebuild \
        -workspace ios/reactnativetest.xcworkspace \
        -scheme reactnativetest \
        clean archive \
        -sdk iphoneos \
        -configuration Debug \
        -UseModernBuildSystem=NO \
        -archivePath $PWD/reactnativetest \
        CODE_SIGNING_ALLOWED=NO"